car-following-state-obs:
  local_dir: ~/tmp
  env: StateObs
  run: PPO
  num_samples: 1
  checkpoint_freq: 10
  checkpoint_at_end: true
  stop:
    episode_reward_mean: 99999
    timesteps_total: 3e6
  ray_resources:
    num_cpus: 40
    num_gpus: 0
  config:
    num_workers: 32
    framework: torch
    # environment
    env_config:
      subsample_road: 10
      task: CarFollowing
      trace_paths: [~/data/20190205-102931_blue_prius_devens_rightside]
      mesh_dir: ~/data/old_vista_mesh_lib_calib/
      init_agent_range: [6, 12]
      collision_overlap_threshold: 0.05
      motion_model: constant_speed # motion model for other non-controllable agents
      respawn_distance: 15
      speed_scale_range: [0.0, 0.8] # only used for random speed motion model
      in_range_mul: [1.1, 1.3]
      wrappers: [ContinuousKinematic, DistanceReward]
      wrappers_config:
        ContinuousKinematic:
          d_curvature_bound: [-5., 5.]
          d_velocity_bound: [-15., 15.]
        DistanceReward:
          reward_coef: 0.001
    observation_filter: MeanStdFilter
    callbacks: BasicCallbacks
    # policies
    multiagent:
      policies: [default_policy]
      policies_to_train: [default_policy]
      policy_mapping_fn: all_to_default
    # MDP-related
    gamma: 0.99
    rollout_fragment_length: 200
    # sgd-related
    lr: 0.0002
    lr_schedule: null
    num_sgd_iter: 8
    train_batch_size: 32000
    sgd_minibatch_size: 512
    # value function
    vf_loss_coeff: 1.0
    vf_clip_param: 1000.0
    # PPO-specific
    entropy_coeff: 0.01
    entropy_coeff_schedule: null
    lambda: 0.95
    kl_coeff: 0.2
    kl_target: 0.01
    clip_param: 0.3
    # model
    model:
      vf_share_layers: false
      fcnet_hiddens: [32, 32]
      fcnet_activation: relu
      custom_action_dist: TorchBeta # prevent inf logprob
      custom_model_config:
        custom_action_dist_config:
          low: [-5., -15.]
          high: [5., 15.]