### Data ###
dataset:
  type: il_event_dataset

  trace_paths: [
    $DATA_DIR/traces/20210910-145502_lexus_mit_dry_lidarevent_ABAB,
    # $DATA_DIR/traces/20210909-160119_lexus_mit_rain_lidarevent_A2,
    $DATA_DIR/traces/20210909-162014_lexus_mit_rain_lidarevent_B2,
  ]

  trace_config:
    master_sensor: lidar_3d

  event_camera_config:
    use_synthesizer: False


val_dataset:
  trace_paths: [
    $DATA_DIR/traces/20210910-152003_lexus_mit_dry_lidarevent_A,
    $DATA_DIR/traces/20210909-165739_lexus_mit_rain_lidarevent_B,
  ]

### Model ###
model:
  extractors:
    event_camera:
      name: convnet_gn
  estimator:
    name: deterministic

### Logging ####
save_every_iters: 1e3
