test_dataset: # default set as trainset
  trace_paths: [
    $DATA_DIR/traces/20210527-131252_lexus_devens_center_outerloop,
    $DATA_DIR/traces/20210527-131709_lexus_devens_center_outerloop_reverse,
    $DATA_DIR/traces/20210826-134807_lexus_devens_outerloop,
    $DATA_DIR/traces/20210826-135430_lexus_devens_outerloop_reverse,
    $DATA_DIR/traces/20210826-190914_lexus_devens_outerloop,
    $DATA_DIR/traces/20210826-191326_lexus_devens_outerloop_reverse,
  ]

  camera_config:
    use_synthesizer: True

  trace_config:
    road_width: 6
    reset_mode: uniform # start from 0 frame index
