### Data ###
dataset:
  type: gpl_rgb_dataset

  car_config:
    lookahead_road: True

  buffer_size: 1


### Model ###
model:
  extractors:
    camera:
      name: convnet
  estimator:
    name: deterministic
