### Data ###
dataset:
  type: null # NOTE: to be set
  trace_paths: [
    $DATA_DIR/traces/20210609-122400_lexus_devens_outerloop_reverse,
    $DATA_DIR/traces/20210609-123703_lexus_devens_outerloop,
    $DATA_DIR/traces/20210609-133320_lexus_devens_outerloop,
    $DATA_DIR/traces/20210609-154525_lexus_devens_sideroad,
    $DATA_DIR/traces/20210609-154745_lexus_devens_outerloop_reverse,
    $DATA_DIR/traces/20210609-155238_lexus_devens_outerloop,
    $DATA_DIR/traces/20210609-155752_lexus_devens_subroad,
    $DATA_DIR/traces/20210609-175037_lexus_devens_outerloop_reverse,
    $DATA_DIR/traces/20210609-175503_lexus_devens_outerloop,
    $DATA_DIR/traces/20210613-171636_lexus_devens_outerloop,
    $DATA_DIR/traces/20210613-172102_lexus_devens_outerloop_reverse,
    $DATA_DIR/traces/20210613-194157_lexus_devens_subroad,
    $DATA_DIR/traces/20210613-194324_lexus_devens_subroad_reverse,
  ]

  trace_config:
    road_width: 4
    reset_mode: default
    master_sensor: front_center

  car_config:
    length: 5.
    width: 2.
    wheel_base: 2.78
    steering_ratio: 14.7

  camera_config:
    name: front_center
    rig_path: ../examples/RIG.xml
    size: [200, 320]
    depth_mode: FIXED_PLANE
    use_lighting: False

  reset_config:
    x_perturbation: [-1.0, 1.0]
    yaw_perturbation: [-0.04, 0.04]
    yaw_tolerance: 0.01

  optimal_control_config:
    lookahead_dist: 10
    dt: 0.333333
    Kp: 0.5

  buffer_size: 1000
  snippet_size: 100
  shuffle: True
  batch_size: 1

val_dataset: # default set as trainset
  trace_paths: [
    $DATA_DIR/traces/20210527-131252_lexus_devens_center_outerloop,
    $DATA_DIR/traces/20210527-131709_lexus_devens_center_outerloop_reverse,
  ]
  batch_size: 64


### Model ###
model:
  extractors:
    camera:
      name: convnet
  estimator:
    name: deterministic


### Training ###
n_iters: 4e5

optimizer:
  name: Adam
  cfg:
    lr: 0.0001

objective:
  name: MSELoss
  cfg: 
    weight: 1e5


### Logging ###
log_every_iters: 1e2
val_every_iters: 4e3
val_total_iters: 1e4
save_every_iters: 4e4
