### Data ###
dataset:
  type: gpl_lidar_dataset
  trace_paths: [
    $DATA_DIR/traces/20210726-131322_lexus_devens_center,
    $DATA_DIR/traces/20210726-131912_lexus_devens_center_reverse,
    $DATA_DIR/traces/20210726-154641_lexus_devens_center,
    $DATA_DIR/traces/20210726-155941_lexus_devens_center_reverse,
    $DATA_DIR/traces/20210726-184624_lexus_devens_center,
    $DATA_DIR/traces/20210726-184956_lexus_devens_center_reverse,
    $DATA_DIR/traces/20210728-203206_lexus_devens_center_night,
    $DATA_DIR/traces/20210728-203206_lexus_devens_center_night,
    $DATA_DIR/traces/20210728-203627_lexus_devens_center_night_reverse,
  ]

  buffer_size: 1000
  batch_size: 1

  trace_config:
    road_width: 6
    master_sensor: lidar_3d

  car_config:
    lookahead_road: True
    road_buffer_size: 50

  reset_config:
    x_perturbation: [-1.0, 1.0]
    yaw_perturbation: [-0.2, 0.2]

  snippet_size: 30

mp_start_method: spawn

val_dataset: # default set as trainset
  trace_paths: [
    $DATA_DIR/traces/20210728-204515_lexus_devens_center_night,
  ]
  batch_size: 1

## Training ###
# n_iters: 500
n_iters: 5e5

optimizer:
  name: Adam
  cfg:
    lr: 0.0001

### Logging ###
log_every_iters: 1e2
val_every_iters: 1e3
val_total_iters: 3e2
save_every_iters: 1e3



### Model ###
model:
  extractors:
    lidar:
      name: minkowskinet
  estimator:
    name: deterministic
