### Data ###
dataset:
  type: gpl_lidar_dataset
  trace_paths: [
    $DATA_DIR/traces/20210726-131322_lexus_devens_center,
    $DATA_DIR/traces/20210726-131912_lexus_devens_center_reverse,
    $DATA_DIR/traces/20210726-154641_lexus_devens_center,
    $DATA_DIR/traces/20210726-155941_lexus_devens_center_reverse,
    $DATA_DIR/traces/20210726-184624_lexus_devens_center,
    $DATA_DIR/traces/20210726-184956_lexus_devens_center_reverse,
    $DATA_DIR/traces/20210728-203206_lexus_devens_center_night,
  ]

  buffer_size: 1000

  trace_config:
    road_width: 6
    master_sensor: lidar_3d

  car_config:
    lookahead_road: True
    road_buffer_size: 50

mp_start_method: spawn

val_dataset: # default set as trainset
  trace_paths: [
    $DATA_DIR/traces/20210726-184956_lexus_devens_center_reverse,
    $DATA_DIR/traces/20210728-204515_lexus_devens_center_night,
  ]
  batch_size: 1

## Training ###
# n_iters: 500
n_iters: 5e5

### Logging ###
# log_every_iters: 10
# val_every_iters: 100
# val_total_iters: 1e2
log_every_iters: 1e2
val_every_iters: 5e3
val_total_iters: 1e2


### Model ###
model:
  extractors:
    lidar:
      name: pointnet
  estimator:
    name: deterministic
