### Data ###
dataset:
  type: gpl_event_dataset

  car_config:
    lookahead_road: True
    road_buffer_size: 50

mp_start_method: spawn


### Model ###
model:
  extractors:
    event_camera:
      name: convnet
  estimator:
    name: deterministic
