### Data ###
dataset:
  type: il_lidar_dataset
  trace_paths: [
    $DATA_DIR/traces/20210726-131322_lexus_devens_center,
    $DATA_DIR/traces/20210726-131912_lexus_devens_center_reverse,
    $DATA_DIR/traces/20210726-154641_lexus_devens_center,
    $DATA_DIR/traces/20210726-155041_lexus_devens_rightside,
    $DATA_DIR/traces/20210726-155640_lexus_devens_rightside_reverse,
    $DATA_DIR/traces/20210726-155941_lexus_devens_center_reverse,
    $DATA_DIR/traces/20210726-184624_lexus_devens_center,
    $DATA_DIR/traces/20210726-184956_lexus_devens_center_reverse,
    $DATA_DIR/traces/20210728-203206_lexus_devens_center_night,
    $DATA_DIR/traces/20210728-203627_lexus_devens_center_night_reverse,
    $DATA_DIR/traces/20210728-204036_lexus_devens_center_nolight_reverse,
  ]

  trace_config:
    road_width: 6
    master_sensor: lidar_3d

  lidar_config:
    use_synthesizer: False

val_dataset:
  trace_paths: [
    $DATA_DIR/traces/20210728-204515_lexus_devens_center_night,
  ]


### Model ###
model:
  extractors:
    lidar:
      name: pointnet
  estimator:
    name: deterministic