### Data ###
dataset:
  type: il_rgb_dataset

  trace_paths: [
    $DATA_DIR/traces/20210910-153337_lexus_mit_dry_rgb_ABAB,
  ]

  camera_config:
    use_synthesizer: False

val_dataset:
  trace_paths: [
    $DATA_DIR/traces/20210910-152951_lexus_mit_dry_rgb_B,
  ]


### Model ###
model:
  extractors:
    camera:
      name: convnet_gn
  estimator:
    name: deterministic


### Training ###
n_iters: 4e5

  
### Logging ###
log_every_iters: 1e2
val_every_iters: 8e3 #4e3
val_total_iters: 5e2 #2e3
save_every_iters: 8e3