test_dataset:
  trace_paths: [
    $DATA_DIR/traces/20210613-171636_lexus_devens_outerloop,
    $DATA_DIR/traces/20210613-172102_lexus_devens_outerloop_reverse,
  ]

  camera_config:
    use_synthesizer: True

  trace_config:
    road_width: 4
    reset_mode: uniform