### Data ###
dataset:
  type: il_lidar_dataset
  trace_paths: [
    $DATA_DIR/traces/20210910-145502_lexus_mit_dry_lidarevent_ABAB,
    $DATA_DIR/traces/20210909-162014_lexus_mit_rain_lidarevent_B2,
  ]

  buffer_size: 1000
  batch_size: 1

  trace_config:
    road_width: 6
    master_sensor: lidar_3d

  lidar_config:
    use_synthesizer: False

  snippet_size: 30

val_dataset:
  trace_paths: [
    $DATA_DIR/traces/20210910-152003_lexus_mit_dry_lidarevent_A,
    $DATA_DIR/traces/20210909-165739_lexus_mit_rain_lidarevent_B,
  ]
  batch_size: 1


log_every_iters: 1e2
val_every_iters: 1e3
val_total_iters: 3e2
save_every_iters: 1e3


### Model ###
model:
  extractors:
    lidar:
      name: minkowskinet
  estimator:
    name: deterministic
