test_dataset:
  trace_paths: [
    $DATA_DIR/traces/20210728-204515_lexus_devens_center_night,
  ]

  camera_config:
    use_synthesizer: True

  trace_config:
    road_width: 4
    reset_mode: uniform
