lane-following-seg-pretrained:
  local_dir: ~/tmp
  env: LaneFollowing
  run: PPO
  num_samples: 1
  checkpoint_freq: 10
  checkpoint_at_end: true
  stop:
    episode_reward_mean: 99999
    timesteps_total: 3e6
  ray_resources:
    num_cpus: 40
    num_gpus: 1
  config:
    num_workers: 10
    num_gpus: 0.2
    num_gpus_per_worker: 0.08
    framework: torch
    # environment
    env_config:
      trace_paths: [~/data/traces/20210527-131252_lexus_devens_center_outerloop]
      reward_mode: default
      wrappers: [PreprocessObservation, BasicManeuverReward]
      wrappers_config:
        PreprocessObservation:
          fx: 3 # NOTE: make sure image size is at least 300-400
          fy: 3
          custom_roi_crop: [33, 88, 135, 243] # NOTE: include sky for segmentation pretrained model
          random_gamma: [0.5, 1.5]
          color_jitter: [0.5, 0.7, 0.5, 0.0] # brightness / contrast / saturation / hue
          imagenet_normalize: true
        BasicManeuverReward:
          center_coeff: 0.01
          jitter_coeff: 0.0
    observation_filter: NoFilter
    callbacks: BasicCallbacks
    # policies
    multiagent:
      policies: [default_policy]
      policies_to_train: [default_policy]
      policy_mapping_fn: all_to_default
    # MDP-related
    gamma: 0.99
    rollout_fragment_length: 200
    # sgd-related
    lr: 0.0002
    lr_schedule: null
    num_sgd_iter: 8
    train_batch_size: 32000
    sgd_minibatch_size: 512
    # value function
    vf_loss_coeff: 1.0
    vf_clip_param: 1000.0
    # PPO-specific
    entropy_coeff: 0.01
    entropy_coeff_schedule: null
    lambda: 0.95
    kl_coeff: 0.2
    kl_target: 0.01
    clip_param: 0.3
    # model
    model:
      vf_share_layers: true
      custom_model: SegPretrainedNet
      conv_filters: []
      conv_activation: relu
      custom_action_dist: TorchBeta # prevent inf logprob
      custom_model_config:
        # ade20k-mobilenetv2dilated-c1_deepsup, ade20k-resnet18dilated-ppm_deepsup, ade20k-resnet50-upernet
        seg_model_name: ade20k-mobilenetv2dilated-c1_deepsup # CHANGE THIS
        seg_out_channel: 4 # CHANGE THIS: 4, 4, 32
        # we want in RIG.xml format roi = [270, 264, 405, 729], where video size [600, 960]
        # we are reading stream with shape [200, 320] --> target RIG.xml format roi = [90, 88, 135, 243]
        # custom_roi_crop [33, 88, 135, 243] gives image shape [102, 155]
        # fx=fy=3 gives imsage shape [306, 465]
        # thus feat_roi_crop = [(90-33)*3=171, 0, 306, 465] in image ([306, 465]) pixel unit
        # double-check by (306-171) == (135-90)*3
        feat_roi_crop: [171, 0, 306, 465] # NOTE: unit is image pixel not based on feature map dimension
        policy_hiddens: [4248, 1024, 2] # CHANGE THIS: 4248, 4248, 4800
        policy_activation: relu
        policy_dropout: 0.5
        value_fcnet_hiddens: [4248, 1024, 1] # CHANGE THIS: 4248, 4248, 4800
        value_fcnet_activation: relu
        value_fcnet_dropout: 0.5
        custom_action_dist_config:
          low: -0.3
          high: 0.3