test_dataset:
  type: il_event_dataset

  trace_paths: [
    $DATA_DIR/traces/20210826-191326_lexus_devens_outerloop_reverse
  ]

  event_camera_config:
    use_synthesizer: False

  trace_config:
    road_width: 4
    reset_mode: segment_start # start from 0 frame index
    master_sensor: front_center

  batch_size: 64
  snippet_size: 999999 # make sure we loop through the entire trace
