test_dataset:
  type: il_event_dataset

  trace_paths: [
    $DATA_DIR/traces/20210910-152003_lexus_mit_dry_lidarevent_A
  ]

  event_camera_config:
    use_synthesizer: False

  trace_config:
    road_width: 4
    reset_mode: segment_start # start from 0 frame index
    master_sensor: lidar_3d

  batch_size: 64
  snippet_size: 999999 # make sure we loop through the entire trace
